### ISSUE TITLE
Weiße Seite nach Installation (nginx)

### ISSUE THREAD

**Issue by STX2k** [phiilu/mailman#10]
Hey, 

Danke erstmal für Mailman, bin durch das Tutorial von Herr Leistner auf dein Webinterface aufmerksam geworden. Ich hab es nicht in einem Docker laufen sondern per Hand aufgesetzt. Nun die Installation lief fehlerlos. Gestartet wurde Mailman auch erfolgreich. Hab ein Reverse Proxy im nginx angelegt aber ich erhalte nur eine weiße Seite.

location /mailman/ {
        proxy_pass http://localhost:4000/;
       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     }

Er loggt auch meinen Zugriff: 

0|mailman  | Mailman is running on port 4000
0|mailman  | GET / 200 6.671 ms - 636
0|mailman  | GET / 304 2.629 ms - -
0|mailman  | GET / 200 1.185 ms - 636
0|mailman  | GET / 200 0.540 ms - 636
0|mailman  | GET / 200 0.580 ms - 636
0|mailman  | GET / 200 1.541 ms - 636
0|mailman  | GET /static/css/main.ace391c0.css 200 1.312 ms - 10430
0|mailman  | GET /static/js/main.49e128ea.js 200 0.704 ms - 769518
0|mailman  | GET /favicon.ico 200 2.220 ms - 3870

Aber die Seite bleibt leider einfach weiß. 

Hab ich was vergessen zu konfigurieren ? Bin eigentlich genau nach deiner Anleitung gegangen. 

Gruß STX

**Comment by STX2k** [comment]
Okay kleines Update. Der Server von Mailman lauscht automatisch auf der IP Adresse des Servers. Ich würde jedoch gern nur auf localhost lauschen lassen und mittels nginx einbinden. Gibt es eine Möglichkeit dies einzustellen? 

Hatte schon getestet ob MAILMAN_HOST=127.0.01 funktioniert ;D

Grüße STX

**Comment by hibas123** [comment]
Um dein Problem mit dem lauschen auf der ip des Servers zu beheben solltest du vll. eine Firewall davorsetzen (z.B. ufw oder direkt iptables). Du kannst das ganze aber auch in dem Quellcode ändern indem du in src/index.js aus:
const server = app.listen(port, () =>
  console.log(`Mailman is running on port ${port}`)
);
Das machst:
const server = app.listen(port, MAILMAN_HOST,() =>
  console.log(`Mailman is running on port ${port}`)
);

Du musst aber MAILMAN_HOST in der .env Datei setzten.

Dein anderes Problem angeht, kann ich jetzt hier wenig sagen, aber kommen die Dateien denn richtig bei dir im Browser an (dev-tools öffnen unter Netzwerk und mal unter Response bei den einzelnen Anfragen schauen, wenn du Chrome oder Firefox benutzt). Wenn da alles ok ist, vll. mal in der JavaScript Konsole nach Fehlern schauen und die mal hier posten.

**Comment by phiilu** [comment]
Hi,

das Problem mit der weißen seite lag nicht an NGINX. Deine Konfiguration sollte passen. Es war ein Problem mit dem Frontend Framework. Ich habe dazu die README etwas angepasst: 

[https://github.com/phiilu/mailman#create-a-env-file](https://github.com/phiilu/mailman#create-a-env-file)

Das was @hibas123 vorgeschlagen hat, habe ich nun auch implementiert und du kannst nun in der .env Datei den MAILMAN_HOST auf 127.0.0.1 setzen. Danach lauscht Mailman auf localhost.

**Comment by STX2k** [comment]
Danke für die Rückmeldung. Ich hab es nochmal komplett neu aufgesetzt. Komischerweise konnte Mailman sich nicht an localhost binden. Naja ich hab jetzt via IPTables gelöst. 

Aber vielen dank nochmal für dein Mailman :)

**Comment by phiilu** [comment]
Sehr gut :)

Bitte gerne und einfach ein Ticket öffnen falls du noch weitere Probleme haben solltest!
