### ISSUE TITLE
Quota Fails

### ISSUE THREAD

**Issue by philliplurge** [phiilu/mailman#12]
Hey

Ich habe heute dein Mailman Setup mittels Docker Installiert.
und habe Bemertk dass die Quota Berechnung Extremst Falsch ist.

Weil 5GB Sind laut mailman "5370"
Währe da "5120" nicht eher Richtig?

Liebe Grüße

**Comment by Lonkey** [comment]
Ich vermute mal, dass kommt von einer fehlerhaften Umrechnung von MB (Dezimalpräfix) in MiB (Binärpräfix).

Denn 5120MiB entsprechen 5368,709 MB, also gerundet 5370 MB.

**Comment by phiilu** [comment]
Stimmt Mailman stellt die Quota in Mebibyte dar. Warum MB statt MiB steht, liegt wohl daran, dass das `bytes.js` node_module nicht die vorhergesehenen Abkürzungen verwendent.

Dazu gibt es bereits ein Issue: visionmedia/bytes.js#26 

Es macht natürlich mehr Sinn nicht die Mebi- Variante zu verwenden, da der Mailserver die Quotas auch nicht nicht in Mebi interpretiert.

**Comment by phiilu** [comment]
Mailman sollte nun quotas korrekt anzeigen:

1024 MB --> 1 GB
2048 MB --> 2 GB
5120 MB --> 5 GB

usw.
