### ISSUE TITLE
Docker Container startet nicht korrekt

### ISSUE THREAD

**Issue by dominikscher** [phiilu/mailman#15]
Hallo,

die Docker Installation funktioniert nicht. Nach dem starten des Docker Containers ist der Port 4000 nicht erreichbar. Ist dieses Problem bekannt?

Viele Grüße
Dominik

**Comment by phiilu** [comment]
Sie dir mal diese Zeile in deiner .env Konfiguration an:

https://github.com/phiilu/mailman/blob/1fa823d7bb7be82d5de4dc2aad21efa31c569874/sample.env#L5

Probier die Variable auf `0.0.0.0` zu ändern und starte einen neuen Container. Falls Mailman immer noch nicht erreichbar sein sollte muss ich mir das noch einmal genauer testen.

**Comment by dominikscher** [comment]
Hi,

danke für die schnelle Antwort!

Jetzt kann ich die Website zwar erreichen und es wird auch in den Docker logs gezeigt, aber es gibt keinen Seiteninhalt. 

![grafik](https://user-images.githubusercontent.com/10786086/34685099-8ab78ed6-f4a7-11e7-9e46-16aeb1e2fefb.png)

**Comment by dominikscher** [comment]
Hi,

danke für die schnelle Antwort!

Es geht jetzt, leider kann ich mich nicht mit meim Admin Account einloggen.

![grafik](https://user-images.githubusercontent.com/10786086/34685776-c6dc2096-f4a9-11e7-90f3-b30e72b5c770.png)

Das Passwort ist definitiv richtig.

**Comment by Lonkey** [comment]
Möglicherweise sind die Zugangsdaten zur Datenbank in der sample.env inkorrekt? Das könnte irrtümlicherweise auch einen 401 Status-Code erzeugen.

**Comment by phiilu** [comment]
Entweder es ist das was @Lonkey sagt oder dein erzeugter Hash aus dem Blog Eintrag ist nicht richtig in der Datenbank gespeichert?

Kannst du das eventuell überprüfen?

**Comment by dominikscher** [comment]
Ich habe das Problem gefunden! Ich habe meine Passwörter ohne "{SHA512-CRYPT}" davor abgespeichert, weil das dass andere Webinterface nicht verstanden hat.

**Comment by phiilu** [comment]
Sehr gut das du den Fehler beheben konntest 😄
