### ISSUE TITLE
BUG: Deployment in subfolder is broken

### ISSUE THREAD

**Issue by miili** [phiilu/mailman#17]
Deployed in subfolder like `/mailman` is not working.

Appears like the api paths in `client/src/services/api.js` are not mapped correctly.

**Comment by phiilu** [comment]
Thank you! I will have a look at this!

**Comment by phiilu** [comment]
Do you also get a white page? If so I have written on how to deploy Mailman in a subfolder in #19

**Comment by miili** [comment]
Yes I followed that deployment guide in the README, seems to be same.

**Comment by phiilu** [comment]
Yeah I just realized that the API paths were not using the basename prefixes like for example: `/mailman`

So you got it working now?

**Comment by miili** [comment]
Nope, deployed it on a subdomain. Yet, would be nice to have have it in a
subfolder.

**Comment by phiilu** [comment]
Did you use docker? 
If so I have updated the documentation on how to use it with a subfolder. 
This would be the easiest way to deploy!
