### ISSUE TITLE
White page

### ISSUE THREAD

**Issue by shoujii** [phiilu/mailman#19]
Hey there,

I'm trying to include mailman into my Server installation Script:

But after installing im getting a white page similiar to:
https://github.com/phiilu/mailman/issues/10

MAILMAN_HOST=0.0.0.0 = binds to IP
127.0.0.1 doesnt work at all.

Edit:
I'm installing mailman with this configuration:
https://github.com/shoujii/NeXt-Server/blob/master/script/mailman.sh

**Comment by Lonkey** [comment]
Why don't you use the docker image?

1. Add the official docker apt repository
`sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable"`

2. Install Docker
`sudo apt-get update && apt-get install docker-ce`

3. Pull the latest mailman docker image
`docker pull phiilu/mailman:latest`

4. Download and edit the latest sample.env
[https://github.com/phiilu/mailman/blob/master/sample.env](url)

5. Start the container
`docker run -d -p 4000:4000 --net="host" --env-file /path/to/env/sample.env --restart=always --name mailman phiilu/mailman`

**Comment by shoujii** [comment]
Docker is not an option.
I'm trying to include it into a script / deploy or manually and it doesn't work as intended or I'm doing smth wrong.
The described fix in #10 doesn't work too.

**Comment by phiilu** [comment]
I will try to deploy Mailman using your script and report back if I found a solution :)

**Comment by phiilu** [comment]
I can see in your script that you want deploy mailman on the `/mailman` location.

Have you seen the instructions in the [Readme ](https://github.com/phiilu/mailman#create-a-env-file)what you need to do?

These steps need to be done BEFORE you build mailman!

1. open `mailman/client/package.json` and change `"homepage": "http://localhost:4000/"` to `"homepage": "http://localhost:4000/mailman"`

2. open `mailman/.env` and change `MAILMAN_BASENAME=/` to `MAILMAN_BASENAME=/mailman`

3. build Mailman `npm install && cd client && npm install && cd - && npm run build`

4. kill `pm2` if it is already running with `pm2 kill`

5. start Mailman again `npm start`

Now you should be able to access Mailman on your webserver on /mailman. 

You need to adopt your script and I hope this solves the white page error.

**Comment by shoujii** [comment]
Thanks this fixed it :)
Now it's running on /mailman.

The login isn't working, but I guess that's a bug in my script (using the Leister Email Setup) and the DB password :)

**Comment by phiilu** [comment]
Awesome! Maybe you have the same problem as #15

**Comment by shoujii** [comment]
It was another problem and it's solved, I made mistakes on my side :O
I mentioned your Repo in our Beta Release News, thanks for your work!
