### ISSUE TITLE
Weiße Seite (Apache)

### ISSUE THREAD

**Issue by achmet9948** [phiilu/mailman#22]
Hallo, 

ich habe folgendes Problem. 
Ich habe mailman in der Deployment Version installiert. Hat auch soweit alles funktioniert. Nun hänge ich an dem Punkt, dass ich kein NGNIX habe sondern Apache2. 
Dort habe ich eine neue .conf angelegt und dort den Reserve Proxy und URL Rewrite hinzugefügt. 

Leider bekomme ich beim Aufruf der domain: kis.meinedomain.de/mailman nur eine weiße Seite angzeigt.

Die entsprechende Konfiguration schaut so aus: 

```
<VirtualHost *:443>
ServerName kis.meinedomain.de

[SSLKonfiguration]

RewriteEngine on
RewriteRule ^/mailman$ /mailman/ [R]

ProxyPreserveHost On
ProxyPass /mailman http://localhost:4000/
ProxyPassReverse /mailman http://localhost:4000/
</VirtualHost>
```

Weißt du wo der Fehler liegt?

**Comment by T0biii** [comment]
Ich habe Mailman bei mir auch unter Apache2 laufen.(Funktoniert auch SUPER)
Nur habe ich Mailman in einen Subfolder konfiguriert.

Deswegen ist mein Konfig bisschen anders:

    RewriteEngine on
    RewriteRule ^/mailman$ /mailman/ [L,R]
    ProxyPreserveHost On
    ProxyPass /mailman http://localhost:4000/mailman
    ProxyPassReverse /mailman http://localhost:4000/mailman

**Comment by achmet9948** [comment]
Danke dir. Ich habe meine Konfiguration etwas angepasst. Hatte einen Denkfehler mit dem Subfolder.
Nun funktionniert es. 

```
RewriteEngine on
RewriteRule ^/mailman$ /mailman/ [R]
ProxyPreserveHost On
ProxyPass / http://localhost:4000/
ProxyPassReverse /mailman http://localhost:4000/
```
