### ISSUE TITLE
Password for admin

### ISSUE THREAD

**Issue by danst0** [phiilu/mailman#24]
Hi,

What ist the standard password for the site admin?

Daniel

**Comment by phiilu** [comment]
Hey

There is no default admin account you have to configure an existing user from your DB as the admin.
Set the MAILMAN_ADMIN variable in .env to your existing email like so:

MAILMAN_ADMIN=daniel@yourdomain.com

See .env configuration options [here](https://github.com/phiilu/mailman#create-a-env-file).

**Comment by FrankP1970** [comment]
Same Problem here.  Anyone who can help?

**Comment by FrankP1970** [comment]
O.K. Problem solved. It is not a mysql/mariadb user, ist is a mailserver user. You have to insert at least one domain and user in the database manually as Thomas Leister explained here : https://thomas-leister.de/mailserver-debian-stretch/#neuen-e-mail-account-anlegen. Doing that and everything works fine. Great work phiilu.

**Comment by Archehandoro** [comment]
> O.K. Problem solved. It is not a mysql/mariadb user, ist is a mailserver user. You have to insert at least one domain and user in the database manually as Thomas Leister explained here : https://thomas-leister.de/mailserver-debian-stretch/#neuen-e-mail-account-anlegen. Doing that and everything works fine. Great work phiilu.

That didn't work for me. I have been using Thomas' setup for a while and created users manually. I can't login with any of the users I have in the db :(
