### ISSUE TITLE
Mailman Autostart

### ISSUE THREAD

**Issue by shoujii** [phiilu/mailman#25]
Gibt es eine Möglichkeit mailman automatisch starten zu lassen?

https://www.npmjs.com/package/node-autostart
hatte ich ausprobiert:
-> npm install -g node-autostart
-> autostart enable -n "mailman" -p "/etc/mailman/" -c "npm start"

allerdings hat das Ganze nicht so geklappt.
Eventuell wäre es auch sinnvoll das Ootb anzubieten :)

Gruß,
Shoujii

**Comment by roberwinkler** [comment]
Hi,
I have the same question....

I tried with an rc.local entry

"cd /home/username/mailman &&npm start >/dev/null &"

which starts mailman - and I can connect to /mailman .... However it does not load the database as it looks.

seems a permission problem - if I start as user > it works ---  but if I start as root (like rc.local) it does not....

regards
richi

**Comment by shoujii** [comment]
pm2 startup

Does the magic :)

**Comment by phiilu** [comment]
With docker there is the options with the flag `--restart=always` and like you already have found out `pm2` offers startup scripts 😄
