### ISSUE TITLE
Login - Something went wrong

### ISSUE THREAD

**Issue by monsterstrumpf** [phiilu/mailman#27]
Good Evening,

before building i used the wrong mail adress for the MAILMAN_ADMIN in .env. I edited it and then eexecuted "npm run build" again. I see the GUI but when i try to authenticate i just get a "Something went wrong". I don't know what to do now more. Isn't there any log which can tell me more about the thing that went wrong? ;)

I apreciate for your work and hope for a soon answer to carry on on this mailserver project :/

Thanks!

**Comment by phiilu** [comment]
Did you use Docker or the pm2 deploy? 

- With the pm2 you can use `pm2 logs` to show all logs.
- With docker there is `docker logs mailman`

But this "Something went wrong" error is most of the time a database connection error.

**Comment by phiilu** [comment]
In the upcoming release of Mailman, there will be better Error messages. Giving the user feedback when the backend is not available, or some other error has happend.

Also closing this, because of no response of the author.
