### ISSUE TITLE
zeigt keine Domains usw. an

### ISSUE THREAD

**Issue by klausschreiber** [phiilu/mailman#29]
Hallo,
ich hatte Mailman anfangs als Docker installiert. Funktionierte schlussendlich dann auch und zeigte alles an. Als ich vor ein paar Tagen drauf ging, waren angeblich keine Domains mehr eingetragen. Ich konnte auch keine hinzufügen. Habe Mailman dann direkt ohne Docker installiert, aber das Problem blieb bestehen. Wenn ich bei Add Domain auf Save Domain klicke, wird der Button grau und nichts passiert.
Die Datenbankzugangsdaten sollten passen. pm2 logs zeigt auch keine Fehler an.
In der Datenbank existieren die Daten noch.
![image](https://user-images.githubusercontent.com/11870076/43597190-a08353ae-9681-11e8-9a9f-e8c85a09cf7f.png)

**Comment by qspweissen** [comment]
Ich habe genau das selbe Problem. Sobald ich htpasswd aktiviere für diese Site, sehe ich keine Daten mehr. Gibts dazu eine Lösung?

**Comment by klausschreiber** [comment]
ich habe mich einfach damit abgefunden, keinen htpasswd Schutz zu aktivieren.

**Comment by phiilu** [comment]
Aktuell ist es besser den Schutz mit htpasswd zu deaktivieren und Mailman mit HTTPS zu konfigurieren. Sobald ich Zeit finde, werde ich schauen ob ich eine Lösung dazu finde.

**Comment by qspweissen** [comment]
> Aktuell ist es besser den Schutz mit htpasswd zu deaktivieren und Mailman mit HTTPS zu konfigurieren. Sobald ich Zeit finde, werde ich schauen ob ich eine Lösung dazu finde.

HTTPS ist selbstverständlich aktiv. Trotzdem würde ich die Seite noch besser schützen wollen ;-) Danke für die Rückmeldung.

**Comment by phiilu** [comment]
I will have a look at it in the upcoming release and hope to figure out, how to use Mailman in combination with `htpasswd`!
