### ISSUE TITLE
No Catchall ("Alias requires Username")

### ISSUE THREAD

**Issue by Rudi1986** [phiilu/mailman#31]
Hi,

yesterday i installed a brand new Mailserver using Thomas Leisters tutorial and your Frontend.
I would like to use catchall-addresses, they work great if i add them directly to the Database, but it's not possible to add a catchall-address in the Frontend because the field Username has to be filled. Is it possible to switch this check off?

Best regards
Rudi

**Comment by hibas123** [comment]
Have a look at #11.

**Comment by phiilu** [comment]
I may address this issue in the upcoming release of Mailman!
