### ISSUE TITLE
Probleme beim Installieren der Apache mit Phusion Passenger 

### ISSUE THREAD

**Issue by philliplurge** [phiilu/mailman#6]
Hallo,

Ich habe da ein kleines Problem unzwar komme ich nicht weiter wo ich die libapache2-mod-passenger installieren soll weil ich Folgenden fehler bekomme.

"sudo apt-get install libapache2-mod-passenger
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 libapache2-mod-passenger : Hängt ab von: libstdc++6 (>= 5.2) aber 4.9.2-10 soll installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete."

wie kann ich dies Beheben ??

**Comment by phiilu** [comment]
Ich schließe dieses Issue aufgrund deines neuen Issue #7
