### ISSUE TITLE
Hilfe?

### ISSUE THREAD

**Issue by philliplurge** [phiilu/mailman#7]
Ich weiß nicht mehr weiter bekomme Folgende Fehlermeldung 

`deploy@mail:~/mailman$ cap install STAGES=production --trace
cap aborted!
LoadError: cannot load such file -- capistrano/scm/git
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/deploy/mailman/Capfile:15:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:689:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:94:in `block in load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:93:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:77:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
/usr/lib/ruby/vendor_ruby/capistrano/application.rb:15:in `run'
/usr/bin/cap:3:in `<main>'
`

**Comment by phiilu** [comment]
Sorry ich habe aktuell nicht wirklich viel Zeit um dir helfen zu können. 

Sobald ich Zeit finde versuche ich `mailman `neu zuschreiben, damit der komplizierte Deployment Prozess mit Rails wegfällt.

Es gibt auch bereits eine neue [Anleitung](https://thomas-leister.de/mailserver-debian-stretch/) die ich gerne mal ausprobieren möchte. Als alternative gibt es [hier](https://github.com/Andreas-Bresch/vmailManage/) eine GUI.

**Comment by phiilu** [comment]
@philliplurge Ich hab bereits angefangen mit dem [rewrite](https://github.com/phiilu/mailman/tree/rewrite). Kann sich nur mehr um Wochen handeln :smile:
